export enum NodeKind {
    ForStmt = 'ForStmt',
    WhileStmt = 'WhileStmt',
    IfStmt = 'IfStmt',
    CallExpr = 'CallExpr',
    BinaryOperator = 'BinaryOperator',
    IntegerLiteral = 'IntegerLiteral',
    DeclRefExpr = 'DeclRefExpr',
    ImplicitCastExpr = 'ImplicitCastExpr',
    UnaryOperator = 'UnaryOperator',
    NamespaceDecl = 'NamespaceDecl',
    EnumDecl = 'EnumDecl',
    DeclStmt = 'DeclStmt',
    EnumConstantDecl = 'EnumConstantDecl',
    ReturnStmt = 'ReturnStmt',
    VarDecl = 'VarDecl',
    StringLiteral = 'StringLiteral',
    ParenExpr = 'ParenExpr',
    UnaryExprOrTypeTraitExpr = 'UnaryExprOrTypeTraitExpr',
    ArraySubscriptExpr = 'ArraySubscriptExpr',
    InitListExpr = 'InitListExpr',
    CompoundStmt = 'CompoundStmt'
}